# Generated by Django 5.2.1 on 2025-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_grade_grade_alter_schedule_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
